name       : corectrl
version    : 1.3.5
release    : 29
source     :
    - https://gitlab.com/corectrl/corectrl/-/archive/v1.3.5/corectrl-v1.3.5.tar.gz : 28a2c6b6156beeaee4f5a66dd70ac76054a8a809dfe1b7e0327a6fe1f0a9e9ac
license    : GPL-3.0-or-later
component  : system.utils
summary    : CoreCtrl allows you to control your computer hardware using application profiles.
description: |
    CoreCtrl is a Free and Open Source GNU/Linux application that allows you to control with ease your computer hardware using application profiles. It aims to be flexible, comfortable and accessible to regular users.
libsplit   : false
builddeps  :
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(botan-2)
    - pkgconfig(quazip)
    - kcoreaddons-devel
rundeps    :
    - qt5-quickcontrols2
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Polkit rules
    install -Dm00644 $pkgfiles/org.corectrl.rules $installdir/usr/share/polkit-1/rules.d/org.corectrl.rules
