name       : corectrl
version    : 1.2.2
release    : 21
source     :
    - https://gitlab.com/corectrl/corectrl/-/archive/v1.2.2/corectrl-v1.2.2.tar.gz : ecfbdb3d99974a64fe6fab90f4bb543154ddc7004eeac14ef65b4ae6e661ca57
license    : GPL-3.0-or-later
component  : system.utils
summary    : CoreCtrl allows you to control your computer hardware using application profiles.
description: |
    CoreCtrl is a Free and Open Source GNU/Linux application that allows you to control with ease your computer hardware using application profiles. It aims to be flexible, comfortable and accessible to regular users.
libsplit   : false
builddeps  :
    - pkgconfig(botan-2)
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kauth-devel
    - kcoreaddons-devel
rundeps    :
    - qt5-quickcontrols2
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # install polkit keyfile to allow running without password
    install -Dm 00644 $pkgfiles/corectrl.keyrules $installdir/usr/share/polkit-1/rules.d/corectrl.keyrules
check      : |
    %ninja_check
