name       : corectrl
version    : 1.0.7
release    : 3
source     :
    - https://gitlab.com/corectrl/corectrl/-/archive/v1.0.7/corectrl-v1.0.7.tar.gz : 66125b1ec1460fd086bdd9b1182cf1f68f810a29cea4c9a3db4192899e0e2688
license    : GPL-3.0-or-later
component  : system.utils
summary    : CoreCtrl allows you to control your computer hardware using application profiles.
description: |
    CoreCtrl is a Free and Open Source GNU/Linux application that allows you to control with ease your computer hardware using application profiles. It aims to be flexible, comfortable and accessible to regular users.
libsplit   : false
builddeps  :
    - pkgconfig(botan-2)
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
rundeps    :
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
